---
name: Alchemy
version: 1.0.0
config-version: 2
profile: default
source-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
data-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: target
clean-targets:
- target
- dbt_modules
vars:
  quickbooks_source:
    quickbooks_schema: quickbooks_ddmr
  asana_source:
    asana_schema: fivetran_asana
  hubspot_source:
    hubspot_schema: fivetran_hubspot
