---
name: Alchemy
version: 1.0.0
config-version: 2
profile: default
source-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
data-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: target
clean-targets:
- target
- dbt_modules
vars:
  asana_source:
    asana_schema: fivetran_asana
  fivetran log_source:
    fivetran log_schema: fivetran_log
  hubspot_source:
    hubspot_schema: fiveran_hubspot
