---
dbtVersion: 0.18.1
jobs:
- name: Throughout the day
  schedule: 0 */5 * * *
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run asana
    command: dbt run --models asana_source asana
  - name: run fivetran log
    command: dbt run --models fivetran_log
  - name: run stripe
    command: dbt run --models stripe
- name: Nightly
  schedule: '15 2 * * * '
  steps:
  - name: run dependencies
    command: dbt deps
  - name: run quickbooks
    command: dbt run --models quickbooks_source quickbooks
